### PR TITLE
Fix #4 Implemented auth support and with exception for mailto scheme

### LINKED ISSUE #4: Not prepend with authentication information portion of a URL
Ok, in 1.0.4 you added support to ignore protocols with non colon-slash-slash. But now it not prepend with auth (the authentication information portion of a URL). Example:

``` javascript
const prependHttp = require('prepend-http');

prependHttp('login:password@site.com');
//=> login:password@site.com

prependHttp('login:password@site.com:1234');
//=> login:password@site.com:1234

prependHttp('login:password@site.com/path/name');
//=> login:password@site.com/path/name
```

In version 1.0.3 it worked correctly.

### PR DESCRIPTION
**Pull request by ruiG**
I followed the regex suggested by @kevva and I added the necessary exception for the case of a mailto uri scheme.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The referenced issue have an unanswered question. What if a username is `mailto`?

This pull request also needs a proper title.

**Comment by ruiG** [comment]
> The referenced issue have an unanswered question. What if a username is mailto?

There is just not enough info in the URI to distinguish between the two different URI schemes that have a somewhat overlapping syntax. 

Specially in cases where the scheme doesn't require `//` before its authority part.

**Comment by sindresorhus** [comment]
@ruiG Yes, that's exactly what https://github.com/sindresorhus/prepend-http/issues/4#issuecomment-244822651 says.

**Comment by sindresorhus** [comment]
Closing for the above reason. See https://github.com/sindresorhus/prepend-http/issues/4#issuecomment-389657421

**Pull request closed without merging**
